# Generated by Django 5.1.7 on 2025-04-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_reset_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='lab',
        ),
        migrations.AddField(
            model_name='subject',
            name='labs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_lab': True}, related_name='practical_labs', to='timetable.classroom'),
        ),
    ]
