# Generated by Django 5.1.7 on 2025-04-03 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_remove_subject_lab_subject_labs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='labs',
        ),
        migrations.AddField(
            model_name='subject',
            name='lab',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_lab': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_lab', to='timetable.classroom'),
        ),
    ]
