# Generated by Django 5.1.5 on 2025-04-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_batch_department_classroom_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=20)),
                ('generated_on', models.DateField()),
                ('timetable_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
