# Generated by Django 5.0.2 on 2025-04-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_timetablestate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableState',
        ),
    ]
