# Generated by Django 5.0.2 on 2025-04-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_delete_timetablestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='practical_teacher',
        ),
        migrations.CreateModel(
            name='BatchTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher')),
            ],
            options={
                'unique_together': {('batch', 'subject')},
            },
        ),
    ]
