# Generated by Django 5.0.2 on 2025-04-27 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_remove_subject_practical_teacher_batchteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_teachers', to='timetable.subject'),
        ),
    ]
