# Generated by Django 5.0.2 on 2025-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_alter_batchteacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='practical_batch_teachers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
